{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka3o-gateway.fullname" . }}
  labels:
    {{- include "kafka3o-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  KGW_API_KEYS: {{ toJson .Values.auth.apiKeys | quote }}
  KGW_PROBE_API_KEY: {{ .Values.auth.probeApiKey | quote }}
  {{- if .Values.kafka.sasl.mechanism }}
  KGW_KAFKA_SASL_USERNAME: {{ .Values.kafka.sasl.username | quote }}
  KGW_KAFKA_SASL_PASSWORD: {{ .Values.kafka.sasl.password | quote }}
  {{- end }}
{{- end }}
