{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka3o-gateway.serviceAccountName" . }}
  labels:
    {{- include "kafka3o-gateway.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
